
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[279] =
    {   0,
        0,    0,  101,   99,    2,    3,   71,   99,   67,   68,
       99,   57,   58,   65,   63,   60,   64,   59,   66,   47,
       47,   61,   62,   74,   73,   75,   76,   99,   46,   55,
       99,   56,   70,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       53,   69,   54,   72,    2,   84,    0,    0,   91,   81,
       92,    0,    0,   89,   79,   87,   80,   88,    0,   90,
       47,   47,   47,    0,   47,   47,   78,   95,   85,   83,
       86,   97,   77,    0,   46,   46,   49,   94,   46,   46,
       46,   46,   46,   46,   46,   46,   14,   46,   46,   46,

       46,   46,   20,   21,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   93,   82,   51,    0,    0,    0,   50,    0,    1,
       47,   48,   96,   98,    0,    0,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   18,   46,
       22,   46,   46,   25,   46,   46,   46,   46,   46,   46,
       32,   46,   46,   46,   46,   46,   46,   40,   46,   46,
       46,   46,   46,    0,    0,    0,   48,   48,   48,   48,
       52,    4,    5,   46,    7,   46,    9,   46,   46,   46,
       46,   15,   46,   46,   19,   23,   46,   26,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   37,   46,   39,
       46,   46,   43,   46,   46,    0,    0,    0,   48,    6,
        8,   10,   11,   46,   46,   16,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   38,   46,   42,
       45,   44,    0,    0,    0,   46,   46,   46,   46,   27,
       28,   46,   46,   31,   33,   34,   35,   36,   41,    0,
        0,    0,   46,   13,   17,   46,   29,   46,    0,   12,
       46,   46,    0,   24,   30,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   26,   26,
       27,   27,   27,   27,   27,   28,   27,   27,   27,   27,
       27,   27,   27,   27,   29,   27,   27,   30,   27,   27,
       31,   32,   33,   34,   27,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   27,   51,   52,   53,   54,   55,   56,   57,
       58,   27,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    2,    2,
        1,    1,    1,    1,    1,    1,    5,    5,    1,    1,
        1,    1,    1,    1,    1,    6,    7,    6,    6,    7,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    6,    7,    7,    7,    7,
        7,    7,    7,    6,    7,    7,    7,    7,    1,    1,
        1,    1
    } ;

static yyconst flex_uint16_t yy_base[286] =
    {   0,
        0,    0,  488,  516,  484,  516,  458,  447,  449,   56,
      438,  516,  516,  447,   52,  516,   51,  516,   50,   51,
       58,  449,  516,   49,  445,   60,  442,  460,    0,  516,
       83,  516,  442,   50,   60,   28,  416,   49,  412,   63,
      411,   75,  423,   72,  419,   37,   74,  405,  407,  399,
      516,   67,  516,  516,  438,  516,   89,  132,  516,  516,
      516,  430,  125,  516,  516,  516,  516,  516,  434,  516,
      138,   84,   89,  164,   89,  100,  516,  414,  516,  516,
      516,  413,  516,  429,    0,    0,  516,  516,  380,  380,
      389,   67,  392,  391,  369,  370,    0,  355,  360,  357,

      353,  350,    0,  346,  350,  350,  340,  349,  348,  340,
       96,  354,  101,  338,  345,  101,   93,  337,  343,  342,
      119,  516,  516,  516,  170,  194,  200,  516,  381,  516,
      516,  169,  516,  516,  378,  377,  335,  321,  329,  324,
      325,  310,  308,  107,  321,  316,  302,  318,    0,  303,
        0,  308,  309,    0,  301,  307,  310,  276,  276,  282,
        0,  273,  120,  273,  273,  275,  281,    0,  280,  270,
      279,  265,  261,  224,  230,  266,  121,  125,  139,  149,
      295,    0,    0,  252,    0,  254,    0,  243,  241,  250,
      235,    0,  249,  241,    0,    0,  234,    0,  248,  235,

      246,  241,  236,  227,  229,  239,  238,    0,  218,    0,
      224,  231,    0,  219,  218,  273,  297,  333,  516,    0,
        0,    0,    0,  207,  208,    0,  207,  202,  198,  197,
      192,  207,  191,  179,  184,  171,  180,    0,  174,    0,
        0,    0,  304,  340,  376,  159,  138,  121,  137,    0,
        0,  131,  116,    0,    0,    0,    0,    0,    0,  383,
      189,  211,  126,    0,    0,  111,    0,   85,  407,    0,
       83,   58,  413,    0,    0,  437,  214,  516,  477,  484,
      489,  492,  499,  506,  509
    } ;

static yyconst flex_int16_t yy_def[286] =
    {   0,
      278,    1,  278,  278,  278,  278,  278,  279,  278,  278,
      280,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  281,  282,  278,
      278,  278,  278,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      278,  278,  278,  278,  278,  278,  279,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  283,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  284,  282,  282,  278,  278,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  278,  278,  278,  278,  278,  278,  278,  283,  278,
      278,  285,  278,  278,  284,  278,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  278,  278,  279,  278,  278,  278,  278,
      278,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  278,  278,  279,  278,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  278,  278,  279,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  278,
      279,  279,  282,  282,  282,  282,  282,  282,  278,  282,
      282,  282,  278,  282,  282,  278,  279,    0,  278,  278,
      278,  278,  278,  278,  278
    } ;

static yyconst flex_uint16_t yy_nxt[579] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   29,
       30,   31,   32,   33,   29,   34,   35,   36,   37,   38,
       39,   29,   40,   29,   29,   41,   29,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   29,   29,   51,   52,
       53,   54,   60,   65,   67,   69,   96,   71,   71,   78,
       79,   70,   68,   66,   71,   71,   97,   61,   72,   73,
       74,   81,   82,   99,   89,   72,   73,   87,  122,  114,
       87,  100,  115,  124,   92,  275,   75,  101,   90,   87,

       91,   93,  103,   75,   76,   94,  110,   74,   95,  106,
      104,   76,  131,  107,   87,  116,  131,  131,  140,  141,
       58,  274,  111,  272,  117,  112,  123,  131,  108,   62,
       87,  118,   62,   87,  131,   87,   57,  131,  158,   57,
      161,   62,  131,  165,  159,  131,  167,  271,   57,  219,
      168,  166,  219,  162,   71,   71,   62,  172,  189,  190,
      125,  173,  205,   57,  270,   72,   73,  219,  268,  267,
      219,  266,   62,  206,  219,   62,  219,   62,  265,   57,
      132,  132,   57,   75,   57,  126,  174,  174,  127,  132,
      264,   76,  219,  124,  219,  174,  177,  178,  132,  132,

      132,  132,  132,  132,  174,  174,  174,  174,  174,  174,
      175,  175,  263,  259,  179,  124,  176,  176,  124,  175,
       58,  258,  180,  257,  256,  176,  255,  254,  175,  175,
      175,  175,  175,  175,  176,  176,  176,  176,  176,  176,
      216,  216,   58,  253,  252,   58,  217,  217,  251,  216,
      250,  249,  248,  247,  246,  217,  242,  241,  216,  216,
      216,  216,  216,  216,  217,  217,  217,  217,  217,  217,
      124,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  218,  218,  229,  228,  227,  226,  225,  243,
      243,  218,  224,  223,  222,  221,  220,   58,  243,  135,

      218,  218,  218,  218,  218,  218,  215,  243,  243,  243,
      243,  243,  243,  244,  244,  214,  213,  212,  211,  210,
      260,  260,  244,  209,  208,  207,  204,  203,  202,  260,
      201,  244,  244,  244,  244,  244,  244,  124,  260,  260,
      260,  260,  260,  260,  200,  199,  198,  197,  196,  245,
      245,  195,  194,  193,  192,  191,  261,  261,  245,  188,
      187,  186,  185,  184,   58,  261,  183,  245,  245,  245,
      245,  245,  245,  182,  261,  261,  261,  261,  261,  261,
      124,  135,  181,  130,  171,  170,  169,  164,  163,  160,
      157,  156,  262,  262,  155,  154,  153,  152,  151,  269,

      269,  262,  150,  149,  148,  147,  146,   58,  269,  145,
      262,  262,  262,  262,  262,  262,  144,  269,  269,  269,
      269,  269,  269,  273,  273,  143,  142,  139,  138,  276,
      276,  137,  273,  136,  134,  133,  130,  128,  276,   55,
      121,  273,  273,  273,  273,  273,  273,  276,  276,  276,
      276,  276,  276,  277,  277,  120,  119,  113,  109,  105,
      102,   98,  277,   88,   84,   83,   80,   77,   64,   63,
       59,  277,  277,  277,  277,  277,  277,   57,   58,   56,
       57,   57,   57,   57,   62,   55,   62,  278,   62,   62,
       62,   85,  278,  278,   85,   85,   86,   86,   86,  129,

      129,  129,  129,  129,  129,  129,  135,  135,  135,  135,
      135,  135,  135,  132,  132,    3,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yyconst flex_int16_t yy_chk[579] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   10,   15,   17,   19,   36,   20,   20,   24,
       24,   19,   17,   15,   21,   21,   36,   10,   20,   20,
       20,   26,   26,   38,   34,   21,   21,   31,   52,   46,
       31,   38,   46,   57,   35,  272,   20,   38,   34,   31,

       34,   35,   40,   21,   20,   35,   44,   20,   35,   42,
       40,   21,   72,   42,   31,   47,   73,   75,   92,   92,
       57,  271,   44,  268,   47,   44,   52,   76,   42,   63,
       31,   47,   63,   31,   73,   31,   58,   72,  111,   58,
      113,   63,   75,  116,  111,   76,  117,  266,   58,  177,
      117,  116,  178,  113,   71,   71,   63,  121,  144,  144,
       58,  121,  163,   58,  263,   71,   71,  179,  253,  252,
      178,  249,   63,  163,  177,   63,  180,   63,  248,   58,
       74,   74,   58,   71,   58,   58,  125,  125,   58,   74,
      247,   71,  179,  261,  180,  125,  132,  132,   74,   74,

       74,   74,   74,   74,  125,  125,  125,  125,  125,  125,
      126,  126,  246,  239,  132,  262,  127,  127,  277,  126,
      261,  237,  132,  236,  235,  127,  234,  233,  126,  126,
      126,  126,  126,  126,  127,  127,  127,  127,  127,  127,
      174,  174,  262,  232,  231,  277,  175,  175,  230,  174,
      229,  228,  227,  225,  224,  175,  215,  214,  174,  174,
      174,  174,  174,  174,  175,  175,  175,  175,  175,  175,
      176,  212,  211,  209,  207,  206,  205,  204,  203,  202,
      201,  200,  176,  176,  199,  197,  194,  193,  191,  216,
      216,  176,  190,  189,  188,  186,  184,  176,  216,  181,

      176,  176,  176,  176,  176,  176,  173,  216,  216,  216,
      216,  216,  216,  217,  217,  172,  171,  170,  169,  167,
      243,  243,  217,  166,  165,  164,  162,  160,  159,  243,
      158,  217,  217,  217,  217,  217,  217,  218,  243,  243,
      243,  243,  243,  243,  157,  156,  155,  153,  152,  218,
      218,  150,  148,  147,  146,  145,  244,  244,  218,  143,
      142,  141,  140,  139,  218,  244,  138,  218,  218,  218,
      218,  218,  218,  137,  244,  244,  244,  244,  244,  244,
      245,  136,  135,  129,  120,  119,  118,  115,  114,  112,
      110,  109,  245,  245,  108,  107,  106,  105,  104,  260,

      260,  245,  102,  101,  100,   99,   98,  245,  260,   96,
      245,  245,  245,  245,  245,  245,   95,  260,  260,  260,
      260,  260,  260,  269,  269,   94,   93,   91,   90,  273,
      273,   89,  269,   84,   82,   78,   69,   62,  273,   55,
       50,  269,  269,  269,  269,  269,  269,  273,  273,  273,
      273,  273,  273,  276,  276,   49,   48,   45,   43,   41,
       39,   37,  276,   33,   28,   27,   25,   22,   14,   11,
        9,  276,  276,  276,  276,  276,  276,  279,    8,    7,
      279,  279,  279,  279,  280,    5,  280,    3,  280,  280,
      280,  281,    0,    0,  281,  281,  282,  282,  282,  283,

      283,  283,  283,  283,  283,  283,  284,  284,  284,  284,
      284,  284,  284,  285,  285,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[101] =
    {   0,
1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.lex"
#line 2 "lexer.lex"
	extern void yyerror(const char*);
	#include <math.h>
	#include <cstdio> 
	#include <map>
	#include <utility>
	#include <vector>
	#include <string>
	#include <iostream>
	#include <cstdlib>
	#include <algorithm>
	#include <iomanip>
	#include <string.h>
	#include "y.tab.h"
	
	using namespace std;	
	extern int lineNum;
	#define YY_DECL extern "C" int yylex()
/*
DEFINE			{WHITESPACE}*#{WHITESPACE}*define
UNDEF			{WHITESPACE}*#{WHITESPACE}*undef 
*/
#line 735 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 127 "lexer.lex"


#line 956 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 516 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 129 "lexer.lex"
{lineNum++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 130 "lexer.lex"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 131 "lexer.lex"
{lineNum++;};	
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "lexer.lex"
{ yylval.sVal = strdup(yytext); return BASE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 133 "lexer.lex"
{ yylval.sVal = strdup(yytext); return BOOL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 134 "lexer.lex"
{ yylval.sVal = strdup(yytext); return BREAK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CASE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CATCH; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CHAR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CLASS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CONST; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CONTINUE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "lexer.lex"
{ yylval.sVal = strdup(yytext); return DEFAULT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 142 "lexer.lex"
{ yylval.sVal = strdup(yytext); return DO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "lexer.lex"
{ yylval.sVal = strdup(yytext); return ELSE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "lexer.lex"
{ yylval.sVal = strdup(yytext); return FALSE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "lexer.lex"
{ yylval.sVal = strdup(yytext); return FINALLY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "lexer.lex"
{ yylval.sVal = strdup(yytext); return FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 147 "lexer.lex"
{ yylval.sVal = strdup(yytext); return GOTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "lexer.lex"
{ yylval.sVal = strdup(yytext); return IF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 149 "lexer.lex"
{ yylval.sVal = strdup(yytext); return IN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "lexer.lex"
{ yylval.sVal = strdup(yytext); return INT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 151 "lexer.lex"
{ yylval.sVal = strdup(yytext); return LONG; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "lexer.lex"
{ yylval.sVal = strdup(yytext); return NAMESPACE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 153 "lexer.lex"
{ yylval.sVal = strdup(yytext); return NEW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "lexer.lex"
{ yylval.sVal = strdup(yytext); return NULL_LIT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 155 "lexer.lex"
{ yylval.sVal = strdup(yytext); return OBJECT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 156 "lexer.lex"
{ yylval.sVal = strdup(yytext); return PARAMS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 157 "lexer.lex"
{ yylval.sVal = strdup(yytext); return PRIVATE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 158 "lexer.lex"
{ yylval.sVal = strdup(yytext); return PROTECTED; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 159 "lexer.lex"
{ yylval.sVal = strdup(yytext); return PUBLIC; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 160 "lexer.lex"
{ yylval.sVal = strdup(yytext); return REF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 161 "lexer.lex"
{ yylval.sVal = strdup(yytext); return RETURN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 162 "lexer.lex"
{ yylval.sVal = strdup(yytext); return STRING; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 163 "lexer.lex"
{ yylval.sVal = strdup(yytext); return STRUCT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "lexer.lex"
{ yylval.sVal = strdup(yytext); return SWITCH; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "lexer.lex"
{ yylval.sVal = strdup(yytext); return THIS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 166 "lexer.lex"
{ yylval.sVal = strdup(yytext); return THROW; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "lexer.lex"
{ yylval.sVal = strdup(yytext); return TRUE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 168 "lexer.lex"
{ yylval.sVal = strdup(yytext); return TRY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 169 "lexer.lex"
{ yylval.sVal = strdup(yytext); return TYPEOF; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 170 "lexer.lex"
{ yylval.sVal = strdup(yytext); return USING; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 171 "lexer.lex"
{ yylval.sVal = strdup(yytext); return VOID; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 172 "lexer.lex"
{ yylval.sVal = strdup(yytext); return WHILE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 173 "lexer.lex"
{yylval.sVal = strdup(yytext); return WHERE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 174 "lexer.lex"
{ yylval.sVal = strdup(yytext); return ID; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 175 "lexer.lex"
{ yylval.iVal = atoi(yytext); return DINT_LITERAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 176 "lexer.lex"
{ yylval.iVal = strtol(yytext, NULL, 16); return HDINT_LITERAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 177 "lexer.lex"
{ yylval.sVal = strdup(yytext); return SIMPLE_ESC_SEQ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 178 "lexer.lex"
{ yylval.sVal = strdup(yytext); return CHAR_LITERAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 179 "lexer.lex"
{ yylval.sVal = strdup(yytext); return REG_STR_LITERAL; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 180 "lexer.lex"
{ yylval.sVal = strdup(yytext); return VER_STR_LITERAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 181 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 182 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 183 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 184 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 185 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 186 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 187 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 188 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 189 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 190 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 191 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 192 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 193 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 194 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 195 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 196 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 197 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 198 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 199 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 200 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 201 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 202 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 203 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 204 "lexer.lex"
{ yylval.sVal = strdup(yytext); return *yytext; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 205 "lexer.lex"
{ yylval.sVal = strdup(yytext); return DQM; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 206 "lexer.lex"
{ yylval.sVal = strdup(yytext); return DCLN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 207 "lexer.lex"
{ yylval.sVal = strdup(yytext); return INCR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 208 "lexer.lex"
{ yylval.sVal = strdup(yytext); return DECR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 209 "lexer.lex"
{ yylval.sVal = strdup(yytext); return RAND; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 210 "lexer.lex"
{ yylval.sVal = strdup(yytext); return ROR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 211 "lexer.lex"
{ yylval.sVal = strdup(yytext); return REQ; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 212 "lexer.lex"
{ yylval.sVal = strdup(yytext); return RNE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 213 "lexer.lex"
{ yylval.sVal = strdup(yytext); return LE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 214 "lexer.lex"
{ yylval.sVal = strdup(yytext); return GE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 215 "lexer.lex"
{ yylval.sVal = strdup(yytext); return APLUS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 216 "lexer.lex"
{ yylval.sVal = strdup(yytext); return AMINUS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 217 "lexer.lex"
{ yylval.sVal = strdup(yytext); return AMULT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 218 "lexer.lex"
{ yylval.sVal = strdup(yytext); return ADIV; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 219 "lexer.lex"
{ yylval.sVal = strdup(yytext); return AMOD; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 220 "lexer.lex"
{ yylval.sVal = strdup(yytext); return AAND; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 221 "lexer.lex"
{ yylval.sVal = strdup(yytext); return AOR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 222 "lexer.lex"
{ yylval.sVal = strdup(yytext); return ACARET; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 223 "lexer.lex"
{ yylval.sVal = strdup(yytext); return LSHIFT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 224 "lexer.lex"
{ yylval.sVal = strdup(yytext); return LSHIFTEQ; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 225 "lexer.lex"
{ yylval.sVal = strdup(yytext); return RSHIFT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 226 "lexer.lex"
{ yylval.sVal = strdup(yytext); return RSHIFTEQ; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 227 "lexer.lex"
{
		char *str = "Error in Lexer";
		yyerror(str);
	}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 232 "lexer.lex"
ECHO;
	YY_BREAK
#line 1529 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 232 "lexer.lex"



int yywrap(void){
	return 1;
}

